# Generated by Django 2.1.1 on 2018-10-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Repositories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_username', models.CharField(max_length=100)),
                ('repository_link', models.CharField(max_length=200)),
                ('repository_name', models.CharField(max_length=200)),
                ('cache_status', models.SmallIntegerField()),
            ],
        ),
    ]
